version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - BASE_URL=${BASE_URL}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017' # Map MongoDB port
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
